image:
  file: .gitpod.Dockerfile

tasks:
  - name: Terminal
  - name: Docker
    init: docker-compose up --no-start --build
    command: docker-compose up
    openMode: split-right

ports:
  - port: 3306
    onOpen: ignore
  - port: 5551
    onOpen: ignore
  - port: 5552
    onOpen: ignore
  - port: 5671
    onOpen: ignore
  - port: 5672
    onOpen: ignore
  - port: 15672
    onOpen: ignore
  - port: 8080
    onOpen: open-preview
  - post: 8033
    onOpen: open-preview
