image:
  file: .gitpod.Dockerfile

tasks:
  - name: Docker
    init: docker-compose build
    command: docker-compose up

ports:
  - port: 3306
    onOpen: ignore
  - port: 4306
    onOpen: ignore
  - port: 5551
    onOpen: ignore
  - port: 5552
    onOpen: ignore
  - port: 5671
    onOpen: ignore
  - port: 5672
    onOpen: ignore
  - port: 15672
    onOpen: ignore
  - port: 8080
    onOpen: open-preview
