image:
  file: .gitpod.Dockerfile

tasks:
  - name: Terminal
  - name: Docker
    init: |
      sudo apt update
      sudo apt install mysql-client
      sudo echo "host=0.0.0.0" >> /etc/mysql/conf.d/mysql.cnf
      sudo echo "user=uberflip" >> /etc/mysql/conf.d/mysql.cnf
      sudo echo "password=pass123" >> /etc/mysql/conf.d/mysql.cnf
      sudo echo "database=university" >> /etc/mysql/conf.d/mysql.cnf
      docker-compose up --no-start --build
    command: docker-compose up
    openMode: split-right

ports:
  - port: 3306
    onOpen: ignore
  - port: 5551
    onOpen: ignore
  - port: 5552
    onOpen: ignore
  - port: 5671
    onOpen: ignore
  - port: 5672
    onOpen: ignore
  - port: 15672
    onOpen: ignore
  - port: 8080
    onOpen: open-preview
