version: "3.9"
services:
  message_broker:
    image: rabbitmq:management
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/conf.d/1-docker.conf
    ports:
      - 15672:15672
      - 5671:5671
      - 5672:5672
      - 5551:5551
      - 5552:5552

  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=university
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MYSQL_USER=uberflip
      - MYSQL_PASSWORD=pass123
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1.schema.sql
    ports:
      - 4306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  pma:
    depends_on: 
      - db
    image: phpmyadmin:5
    volumes:
      - ./config/pphpmyadmin.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=uberflip
      - PMA_PASSWORD=pass123
    ports:
      - 8080:80
